CREATE TABLE hydroData(
	light VARCHAR(255),
	temperature VARCHAR(255),
	airQuality VARCHAR(255),
	liquidLV VARCHAR(255),
	dateCreated DATETIME DEFAULT CURRENT_TIMESTAMP,
	dateUpdated DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)