CREATE TABLE hydroData(
	id INT(11) NOT NULL AUTO_INCREMENT,
	deviceID VARCHAR(255) NOT NULL,
	light VARCHAR(255),
	temperature VARCHAR(255),
	airQuality VARCHAR(255),
	liquidLV VARCHAR(255),
	dateCreated DATETIME DEFAULT CURRENT_TIMESTAMP,
	dateUpdated DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)